chore: re-add index.js
eHealthAfrica/aether-deployment-test pull request #1
Opened 2018-11-06 14:57 UTC by adamvert

2018-11-14 13:22 UTC, quesebifurcan requested changes
Nice, very useful!

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +      ':' + d.getSeconds().toString().padStart(2, '0') + ' ' + logText)
would `d.toLocaleTimeString()` or `d.toISOString()` work here?

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +const generateOptions = (module, entity, payload, method, id, pathExtension) => {
Shadowing `module` built-in here. Can we pick another name for this argument?

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +    uri: `${urls[module]}/${plural}/${id ? id + '/' : ''}${pathExtension ? pathExtension + '/' : ''}`,
Minor nit, but I try to avoid nesting string concatenation inside of template strings.

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +    })
What happens when this fails? Can/should the script keep running without assigning to projectId? Or is this intended to be caught here https://github.com/eHealthAfrica/aether-deployment-test/blob/a358f5d090bbf5c7ede70172014fecf2a52bbbea/index.js#L240?

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +    .then(deleteKernelProject)
What happens if one of these fails? Maybe add a catch block with some info so we can clean up manually?

2018-11-14 13:22 UTC, quesebifurcan commented on index.js
> +let surveyorId, projectId, xFormId
`xFormId` isn't used anywhere, or?

2018-11-14 13:47 UTC, adamvert commented on index.js
> +    })
Yes, that's the intention - but you're right, I could put in some more granular error messages

2018-11-14 13:50 UTC, adamvert commented on index.js
> +let surveyorId, projectId, xFormId
True - a relic from a previous version

2018-11-14 13:50 UTC, adamvert commented on index.js
> +    uri: `${urls[module]}/${plural}/${id ? id + '/' : ''}${pathExtension ? pathExtension + '/' : ''}`,
👍

2018-11-14 13:50 UTC, adamvert commented on index.js
> +const generateOptions = (module, entity, payload, method, id, pathExtension) => {
👍

2018-11-14 13:51 UTC, adamvert commented on index.js
> +      ':' + d.getSeconds().toString().padStart(2, '0') + ' ' + logText)
👍

2018-11-20 09:49 UTC, adamvert commented
@quesebifurcan can you review again please?

2019-08-14 15:21 UTC, merged